import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#3c2f00",
        "on-tertiary-fixed": "#3b0613",
        "surface-container-lowest": "#0b0f10",
        "on-secondary-container": "#342800",
        "surface-container": "#1d2022",
        "secondary-fixed": "#ffe088",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e0e3e5",
        "secondary-fixed-dim": "#e9c349",
        "on-tertiary": "#571c27",
        "outline-variant": "#45464d",
        "primary-container": "#0f172a",
        "on-surface": "#e0e3e5",
        background: "#101415",
        "surface-tint": "#bec6e0",
        "secondary-container": "#af8d11",
        "surface-variant": "#323537",
        primary: "#bec6e0",
        "inverse-on-surface": "#2d3133",
        "tertiary-fixed": "#ffd9dc",
        "surface-dim": "#101415",
        "error-container": "#93000a",
        tertiary: "#ffb2bb",
        surface: "#101415",
        "on-primary-container": "#798098",
        outline: "#909097",
        error: "#ffb4ab",
        "tertiary-container": "#36030f",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed": "#131b2e",
        "tertiary-fixed-dim": "#ffb2bb",
        "on-surface-variant": "#c6c6cd",
        "surface-container-highest": "#323537",
        "on-secondary-fixed": "#241a00",
        "primary-fixed-dim": "#bec6e0",
        "inverse-primary": "#565e74",
        "surface-container-high": "#272a2c",
        "on-tertiary-container": "#b86a75",
        "surface-bright": "#363a3b",
        "on-primary": "#283044",
        secondary: "#e9c349",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed-variant": "#574500",
        "on-background": "#e0e3e5",
        "surface-container-low": "#191c1e",
        "on-tertiary-fixed-variant": "#73323d",
        "on-error": "#690005",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        unit: "8px",
        "container-max": "1200px",
        "margin-mobile": "24px",
        "margin-desktop": "64px",
        "section-gap": "120px",
      },
      fontFamily: {
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Playfair Display'", "serif"],
        "display-lg-mobile": ["'Playfair Display'", "serif"],
        "display-lg": ["'Playfair Display'", "serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Playfair Display'", "serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
      keyframes: {
        shimmer: {
          "0%": { transform: "translateX(-100%) rotate(45deg)" },
          "100%": { transform: "translateX(100%) rotate(45deg)" },
        },
        "pulse-glow": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.8" },
          "50%": { transform: "scale(1.2)", opacity: "1" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-14px)" },
        },
        "spin-slow": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        twinkle: {
          "0%, 100%": { opacity: "0.2" },
          "50%": { opacity: "1" },
        },
      },
      animation: {
        shimmer: "shimmer 3s infinite",
        "pulse-glow": "pulse-glow 2.4s infinite ease-in-out",
        float: "float 6s ease-in-out infinite",
        "spin-slow": "spin-slow 40s linear infinite",
        marquee: "marquee 28s linear infinite",
        twinkle: "twinkle 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
export default config;
